=== OleksiiTkachenkoo/internetshop/src/main/java/com/solvd/internetshop/util/jackson/json/user-schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "id": {
      "type": "integer"
    },
    "firstName": {
      "type": "string"
    },
    "lastName": {
      "type": "string"
    },
    "phone": {
      "type": "string"
    },
    "password": {
      "type": "string"
    },
    "email": {
      "type": "string"
    },
    "address": {
      "type": "object",
      "properties": {
        "city": {
          "type": "string"
        },
        "country": {
          "type": "string"
        }
      },
      "required": [
        "city",
        "country"
      ]
    },
    "age": {
      "type": "integer"
    }
  },
  "required": [
    "id",
    "firstName",
    "lastName",
    "phone",
    "password",
    "email",
    "address",
    "age"
  ]
}

=== OleksiiTkachenkoo/internetshop/src/main/java/com/solvd/internetshop/util/jackson/json/user.json
{
  "id" : 1,
  "firstName" : "Alex",
  "lastName" : "Drake",
  "phone" : "+380933839249",
  "password" : "SD{PK33030-",
  "email" : "drake3@gmail.com",
  "address" :
      {
        "city" : "Kyiv",
        "country" : "Ukraine"
      },
  "age" : 33,

  "id" : 2,
  "firstName" : "Olga",
  "lastName" : "Kotenko",
  "phone" : "+380974935773",
  "password" : "aaaakkkslk399885kkkdlklls;-",
  "email" : "kotik21@gmail.com",
  "address" :
  {
    "city" : "Lviv",
    "country" : "Ukraine"
  },
  "age" : 21
}

=== OleksiiTkachenkoo/internetshop/user1.json
{
  "id" : 1,
  "firstName" : "Alex",
  "lastName" : "Yo",
  "phone" : "+380934987349",
  "password" : "okefkewe324",
  "email" : "so3@gmail.com",
  "age" : 23,
  "address" : {
    "id" : 1,
    "country" : "Ukraine",
    "city" : "Kyiv",
    "street" : "Kyrilenko 23",
    "apartment" : "27",
    "idUser" : 1,
    "idShipment" : 2
  }
}
